### ISSUE TITLE
Update to stable streamlit version

### ISSUE THREAD

**Issue by mmaelicke** [hydrocode-de/RUINSapp#1]
Right now, streamlit is frozen to `0.56.0` although the stable `1.0` has been published.

**Comment by AlexDo1** [comment]
For me, the RUINSapp just started without following any of the frozen dependencies.
But of course I don't know if any functionality within the app relies on the frozen dependencies.

**Comment by mmaelicke** [comment]
Python will ignore these settings, if you have these packages already installed. The requirements are only specified for installation.

**Comment by cojacoo** [comment]
Lets startover and use the current stable versions of all packages. There is no need for the old stuff to remain. It was simply defined as frozen to spare fixing of the many updates.
