### ISSUE TITLE
Checkout different frameworks for Website

### ISSUE THREAD

**Issue by mmaelicke** [hydrocode-de/RUINSapp#16]
Right now, there are three different frameworks I want to test for their suitability to make up the main website:

## goHugo

Hugo is based around markdown files. They are flexible, can be read without the framework, and render nicely in github as well. Additionally, they can be directly included into streamlit if the content of the website should be loadable here as well.
The streamlit apps can be included via their own content page, which just hold a [shortcode](https://gohugo.io/templates/shortcode-templates/) to a boarderless iframe linking the streamlit app.

## sphinx

Sphinx is the de-facto documentation engine for python. It would be nice to have the introduction texts, streamlit apps, and code reference all in one place. Sphinx is built with restructured text, which is similar to markdown. I am as of now not 100% sure how to embed an iframe into a sphinx page.
A possible downside of sphinx is that most templates work with sidebar navigation, which we have to get rid of for the streamlit apps. The templates are built with jinja2 (I think), which is pretty straightforward and could enable us to build our own template.

## react

Another option is to use react. We would go with material design here, which will be very familiar to most users, as most websites nowadays are built this way. The huge advantage is flexibility. I can build anything into the app. The downside is, that this will take time. As long as the website does not get too complicated, the effort to implement should be controllable.

@cojacoo any comment is welcome, otherwise, I will implement a minimal example for all three options and see how things are going:

- [ ] minimal hugo example
- [ ] minimal sphinx example
- [ ] minimal react app

**Comment by cojacoo** [comment]
I like Hugo. I also like the option to work with markdownfiles for both, apps and websites. If I got you right, iframes would be mostly interactive content such as a streamlit app? A url-link would be ok too.

**Comment by mmaelicke** [comment]
I guess we have a plan here, and made the decision in favor of an React app.
