### ISSUE TITLE
netCDF dependency missing?

### ISSUE THREAD

**Issue by mmaelicke** [hydrocode-de/RUINSapp#3]
On startup I get this error: 

```
OSError: [Errno -51] NetCDF: Unknown file format: b'/home/mirko/Dropbox/hydrocode/ruins/RUINSapp/data/weather.nc'
Traceback:
  File "/home/mirko/anaconda3/lib/python3.8/site-packages/streamlit/ScriptRunner.py", line 314, in _run_script
    exec(code, module.__dict__)
  File "/home/mirko/Dropbox/hydrocode/ruins/RUINSapp/RUINSapp.py", line 38, in <module>
    weather, climate = load_alldata()
  File "/home/mirko/Dropbox/hydrocode/ruins/RUINSapp/RUINSapp.py", line 27, in load_alldata
    weather = xr.load_dataset('data/weather.nc')
```

**Comment by mmaelicke** [comment]
@cojacoo which netCDF backend are you using to make xarray open the `weather.nc` file? I tested backends `scipy, netCDF4, h5netCDF` and none of them seemed to work.

**Comment by cojacoo** [comment]
@mmaelicke the file is built with xarray as xr.Dataset of xr.DataArrays. Not sure if this has any version issues? Also not sure which netCDF engine is bound to my xarray.

**Comment by mmaelicke** [comment]
hmm I tried to:

```
import xarray as xr
xr.load_dataset('./weather.nc')
```
as well as explicitly setting the backend `scipy`, `netCDF4`, `h5py` for version 3; 4 and hdf5 format. None of them is recognizing the file. Checked with the versions given in requirements (pretty outdated) and the newest versions on Python 3.8 and 3.9...

BTW: ncview also complains about format issues.

Do you by any chance have the code, which was used to build the netCDF

**Comment by cojacoo** [comment]
@mmaelicke sure. We can perfectly update this. I put it on my list.

**Comment by AlexDo1** [comment]
I just got the RUINSapp working on my PC by installing the backend `netcdf4`.

Originally I received the following error message, but as I said, installing `netcdf4` fixed the error:
![image](https://user-images.githubusercontent.com/23619690/154793936-9940d91b-ba9e-48e8-9704-fa35aed2897c.png)

**Comment by mmaelicke** [comment]
@AlexDo1 you are also using a Mac, just like @cojacoo . I will checkout later on a windows os. Yesterday it did not work with netcdfr installed on my debian machine...

We're getting closer.

**Comment by AlexDo1** [comment]
To my embarrassment, I am also making the first attempts right now on a Windows PC 😄

**Comment by cojacoo** [comment]
Ok friends. The file is `File type: Hierarchical Data Format, version 5` and perfectly well defined on my machine. E.g. I can use https://www.giss.nasa.gov/tools/panoply/ to view and plot it. So I really do not see the issue on my machine. Moreover, I doubt that it is a versioning issue with the older xarray...

**Comment by cojacoo** [comment]
So maybe it is simply misleading to have .nc and not .h5 as an ending?

**Comment by mmaelicke** [comment]
Finally, my windows and ubuntu also had no issues. So it was only my debian system that could not open the files. I suspect, that maybe git-lfs was not installed there. It's the only explanation I can think of right now...

However, I guess we can consider this issue closed...
