### ISSUE TITLE
Missing module

### ISSUE THREAD

**Issue by mmaelicke** [hydrocode-de/RUINSapp#36]
I am right now on the splitting of the app into several apps and solving issues caused by the splitting. This line, however, references an import of a local file that is not present in repository.

https://github.com/hydrocode-de/RUINSapp/blob/ad53bf99e22c676730e655f61acfbde00f3344dd/RUINSapp.py#L799

@cojacoo can you add the file to your RUINSapp repo, so that I can pull it into this version?

**Comment by cojacoo** [comment]
Pls. check https://github.com/cojacoo/get_climate_data

**Comment by cojacoo** [comment]
sorry. pls. check if this dependency is really necessary: https://github.com/woodcrafty/PyETo/tree/master/pyeto

**Comment by jonaslenz** [comment]
pyeto is used in several functions.
there is also one further dependency "spotpy", which can be added in the requirements.txt
