### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by mmaelicke** [hydrocode-de/RUINSapp#5]
Add a LICENSE file and a license statement in the setup.py for PyPI. We can go for a MIT license or a GPL 3. @cojacoo any preferences?

**Comment by cojacoo** [comment]
@mmaelicke no real pref. Mit appears more flexible to me and can include the processed data?

**Comment by mmaelicke** [comment]
included in https://github.com/hydrocode-de/RUINSapp/commit/e5154f83a5fc28ea1996bd893b466bbf6c8733f5
