### ISSUE TITLE
RUINS test website not accessible on /home

### ISSUE THREAD

**Issue by AlexDo1** [hydrocode-de/RUINSapp#50]
@mmaelicke, I told you earlier that I can't access the RUINS test website via my bookmark. This is because the bookmark is http://ruins-test.hydrocode.de/home (where you also land when you enter the website without `/home`, so you would naturally create the bookmark like that), this leads to the error `404 Not Found`.
I can only get to the website with http://ruins-test.hydrocode.de without /home.

I just noticed that all subwebsites are not directly accessible, so also for example http://ruins-test.hydrocode.de/introduction or http://ruins-test.hydrocode.de/weather.

Not sure if this is a bug.

**Comment by mmaelicke** [comment]
Yeah, this is a missing configuration in nginx, which tries to access a `home.html` on the server. I know how to fix it, but it's not a super high priority.
Thanks for reporting

**Comment by mmaelicke** [comment]
This is fixed for the current server (although the route `/home` does not exist anymore). The deployment docs were updated to include SPA configuration.

But you can now access child pages directly ie: `http://ruins.hydrocode.de/app/weather`
