### ISSUE TITLE
Restructure topic_selector the same way as data_selector

### ISSUE THREAD

**Issue by AlexDo1** [hydrocode-de/RUINSapp#52]
Stop using compact_selector() in topic_selector() to get rid of the if-else statement in the topic_selector() function.

Also align with data selector to be consistent.

**Comment by mmaelicke** [comment]
@AlexDo1 `data_selector` also supports language now, this should also be reflected in the topic selector.

**Comment by AlexDo1** [comment]
Sure, I will work on that.

**Comment by mmaelicke** [comment]
This can be closed, as there is no need for a topic selector anymore
