### ISSUE TITLE
`topic_select.topic_select` ignores `topic_list` argument

### ISSUE THREAD

**Issue by mmaelicke** [hydrocode-de/RUINSapp#63]
Hey @AlexDo1,

I started working on the Climate explorer and wanted to recycle the topic_select for the newly created story mode. Unfortunately, the `topic_select` seems to ignore a `topic_list` argument, altough it is read from kwargs here:

https://github.com/hydrocode-de/RUINSapp/blob/06ad9d7f844bac517fea0ff94880159a9644c283/ruins/components/topic_select.py#L22

The component always renders two topics for selection: 'warming' and 'climate indices', no matter what was passed.

The expected behavior is that the rendered topics can be limited by the `topic_list` argument.

**Comment by AlexDo1** [comment]
That's true, the topics 'warming' and 'climate indices' are always displayed.

I can fix that but it is important that the alternative `topic_list` provided in kwargs only consists of topic names precisely matching the standard topic names.

**Comment by mmaelicke** [comment]
Yeah. I would go for a global `dict` in that file, that contains the elements for each topic as another dict or tuple. Then, we can dynamically add entries/keys and also solve the translation issue with another dict.

Something like:
```python
_TOPICS_DE = dict(
  'Warming': dict(img='<image_url/path>', description='blabla'),
'Indices': dict(...), 
)
_TOPICS_EN = dict(...)
```

Then in the main component, we can have the topic list in the seginature defined like:

```python
def selector(..., topic_list: List[str] = 'all'):
  if topic_list == 'all':
    topic_list = list(_TOPICS_EN.keys())
    for topic in topic_list:
      st.markdown(topic['description'])
```
and so on

This is how I started implementing stuff to make climate and weather explorer reuse components

**Comment by mmaelicke** [comment]
We'll close this issue, as topics do not exist anymore
