### ISSUE TITLE
Stripes Plot seems off

### ISSUE THREAD

**Issue by mmaelicke** [hydrocode-de/RUINSapp#66]
@AlexDo1, @lucfr 
 
![image](https://user-images.githubusercontent.com/2826034/164487347-2b4edaf6-7f7b-4861-a861-a8d4784aa15b.png)

The stripes plot seems to be quite off. I guess there is something wrong with the way, the function handles the data. The patterns don't seem to be right. 
For development, I used the `./dev/heatmap.ipynb` notebook. @cojacoo's original function is in there along with my re-implementation using plotly. 
It would be great if anyone of you could double check if it's only my function, that is off, or Conrad's function is also off.
That would be great help for finding the actual issue.

**Comment by cojacoo** [comment]
We will check this with the new dataset. But right now, it does not exhibit obvious issues (compared to what you showed me yesterday).

**Comment by mmaelicke** [comment]
I'll close this issue, as the problem seems to be solved. If it pops up again with the new data, we can re-open
