### ISSUE TITLE
build e2e test, if somehow possible

### ISSUE THREAD

**Issue by mmaelicke** [hydrocode-de/RUINSapp#7]
This is a bit of a challenge. There seems to be no native way, how a streamlit app can be unit-tested. This makes maintenance way more complicated. 

However, few resources I found: 

- https://discuss.streamlit.io/t/access-app-errors-in-pytest/8015/3

Idea is to at least start streamlit apps and check that no `streamlit.exception` output is visible, using selenium.

Other pathway would be to build a thin wrapper around each streamlit app that catches any output on stderr and catches unhandled exceptions. Additionally, any exception handling within the apps needs to be configuable to pass exceptions in *test mode*. Silimar to:

```python
def main_app(debug=False):
  try:
    st.function_could_error()
  except Exception as e:
    if debug:
      raise e
    else:
      st.exception(e)
```

**Comment by AlexDo1** [comment]
Sure I will have a look at it.

As I see it, there are 3 possible ways to test:

- tests page has identical structure to baseline: `self.check_window(name="first_test", level=2)`
- checks that the exact text “streamlit-folium” is present in the app: `self.assert_text("streamlit-folium")`
- use OpenCV to compare a screenshot of the app to a baseline screenshot

The baseline files would need to be updated if anything changes in the structure of the application, but that shouldn't be a problem, just something to keep in mind.


I can try to implement initial tests so we have a basic structure.
But for that, the app has to run on my system first, which I have not tried yet.

**Comment by mmaelicke** [comment]
I think it would be more worth it to check the second solution as outlined in my first comment, first, as implementation will be way easier. I am not sure if exceptions get passed through completely, but that's something we can try easily. The advantage is that this will be less implementation effort, the downside is that we only test for exceptions. 

I think being sure, that there are no exceptions is good enough. We do not really have to test the frontend as well. 
So, if we check for exceptions, we can add a baseline at the very end of the project for the most important content. 

The only thing that we should really **not** do, is use opencv to check the screenshot. That's probably completely over the top.

**Comment by AlexDo1** [comment]
Okay, makes sense.

To implement the suggestion in your first comment, we first need the base skeleton with the main_app and where we run the apps individually, right?

**Comment by mmaelicke** [comment]
yep

**Comment by mmaelicke** [comment]
I have a minimal, simplistic working example with https://github.com/hydrocode-de/RUINSapp/commit/b9c3c02aaff33857f7f9a696d2dbe3929dc1e9cf
