### ISSUE TITLE
Select Aggregate variable globally or for each plot?

### ISSUE THREAD

**Issue by mmaelicke** [hydrocode-de/RUINSapp#76]
This is the current state of the climate explorer, when two parallel coordinate plots are selected:

![image](https://user-images.githubusercontent.com/2826034/169840645-fb0887fe-eede-4398-a815-8bfcea3285c4.png)

The variable is selected globally and affects all plots at the same time. On the one hand, that keeps multiple plots more in line and puts comparison of RCPs or time-spans into focus. On the other hand a comparison of variables (same RCP, same extent, different var) is impossible right now.

@cojacoo, should we move the variable selection into the plot expanders or keep things as they are?

**Comment by mmaelicke** [comment]
@cojacoo, this relates also to #72 as we have to think about control layout, in case you want an optional station filter for each plot as well...

**Comment by cojacoo** [comment]
I can only guess from here (EGU, head full of other things). Our story is not so much about variable interaction but about uncertainty related to observation ADN prediction. Hence a comparison of variables is maybe not the most important feature and a variable selected earlier is easiest to follow along?

**Comment by mmaelicke** [comment]
>  can only guess from here (EGU, head full of other things). Our story is not so much about variable interaction but about uncertainty related to observation ADN prediction. Hence a comparison of variables is maybe not the most important feature and a variable selected earlier is easiest to follow along?

I have the same feeling and would keep it as it is. Deciding to go for a variable selection in each plot is also not so much an implementation issue, than a layout issue. Meaning we can come back to this if needed. Until then, I'll close this issue
