### ISSUE TITLE
Remove Topics

### ISSUE THREAD

**Issue by mmaelicke** [hydrocode-de/RUINSapp#78]
With the new application layout, there is no need for the concept of topics anymore.

We need to:

- [ ] get rid of the topic select component
- [ ] get rid of any reference of topics (texts, selects etc)
- [ ] topic-related configs

To keep the app cleaner, I would do that soon. At the same time, I don't want to lose the topic-select code. My approach: 
copy the topic-select into a newly created `compontents.legacy` submodule. Then push this to a new branch called `legacy-topic-select` and after that remove everything from main branch. 
If we then never ever need the topic selec again, we can simply remove that branch. 

@AlexDo1 or @lucfr  you can go for this issue by assigning yourself

**Comment by AlexDo1** [comment]
I just created the `legacy-topic-select` branch and pushed it to Github.
I will move on to removing topic-related code from the main branch, but wouldn't it be easier to remove the code directly from the `weather-climate-merge` branch where you (@mmaelicke ) already don't use a lot of the topic related code anymore?

**Comment by AlexDo1** [comment]
Okay, so I will start removing topic related code from the `weather-climate-merge` branch.

**Comment by AlexDo1** [comment]
I think I found all occurrences of topic related code (https://github.com/hydrocode-de/RUINSapp/pull/77/commits/d2ecb2f9dc0a2d84bbc99b9357eb8c4ceadf3f2a). 
There was'n really much left.
- I didn't touch [management.py](https://github.com/hydrocode-de/RUINSapp/blob/main/ruins/apps/management.py) as we will completely refactor the code in the future.
- [RUINSapp.py](https://github.com/hydrocode-de/RUINSapp/blob/main/RUINSapp.py) is also an old version of the App which still uses topics, I didn't modify this file either.
- [Intro.md](https://github.com/hydrocode-de/RUINSapp/blob/main/explainer/Intro.md) also still mentions the topics in a broader sense, I think that's okay.
In [Intro.md](https://github.com/hydrocode-de/RUINSapp/blob/main/explainer/Intro.md) we could reformulate the following paragraph:
> **Topical story lines**
> Since a plethora of topics related to changes in climate, weather and possible adaptation exists, we suggest several topics reoccurring in each chapter. These topics can be used as story lines guiding through the app.
