### ISSUE TITLE
Weather data update

### ISSUE THREAD

**Issue by mmaelicke** [hydrocode-de/RUINSapp#81]
@cojacoo distributed new weather and climate data. It's a zip file containing a netCDF file of the dataset in a bias-corrected version and a uncoreccetd version.
@AlexDo1, I will upload the data to the server, so you can download it as well. Please check the contents (there is also a notebook distributed) and give me a short overview on the differences between the old netCDF files and the new one. Maybe renaming the file to match the old pattern is enough. Maybe not.

**Comment by mmaelicke** [comment]
From what I know about the new file:

- weather data is **not** included
- in the old files we were missing the regional climate models, right?
- loading the netCDF files should be really slow **once** per running server or user session, depending on the config. In the final app it will be slow once per server  startup. **But:** we need to profile the memory footprint of the new netCDF to see if the server RAM is enough.

**Comment by AlexDo1** [comment]
I took a look at the files again.

`cordex_krummh_nobias_f32.nc` and `cordex_krummh_nobias_f32_ET.nc` have the same keys, so the same model calculations are included.
`cordex_krummh_nobias_f32_ET.nc` **should** include evapotranspiration data, but the ET-related variables are not included in the file. Do we need evapotranspiration data for RUINS? 

The temporal extent in the old file ranges from 2006-01-01 to 2100-12-31 and the following variables are included: _['T', 'Tmin', 'Tmax', 'Prec', 'Rs', 'RH', 'u2', 'vabar', 'aP', 'EToPM', 'EToPM1', 'EToHG', 'EToSJ', 'EToPT']_.

The data in the new files range from 2005-03-12 to 2096-11-08 and the following variables are included in **both** new files: _['Prec', 'RH', 'Rs', 'T', 'Tmax', 'Tmin', 'aP', 'u2', 'vabar']_ (ET is missing).

I have plotted some data sets and there are also differences between the values of the old and the new data.

I guess the main difference between the datasets is that the new data files include additional 'data providers':
_{'CERFACS-CNRM-CM5',
 'CLMcom-ETH',
 'CanESM2',
 'DWD',
 'EC-EARTH',
 'HadGEM2-ES',
 'M-MPI-ESM-LR',
 'MIROC5',
 'MOHC'}_

> - weather data is not included

I'm not sure about that, the new data files also include historical DWD data.

> - in the old files we were missing the regional climate models, right?

Again not sure, but old data also has the attribute **RCM**.

**Comment by mmaelicke** [comment]
Alright. The fact that there are differences between the old and new data version makes sense, as that is the reason for the update.

Can you check if the DWD data provider data is in line with the content of the old `weather.nc`, in terms of data dimension and temporal index?

**Comment by AlexDo1** [comment]
DWD historical data is not in line with the old `weather.nc`.
The temporal index is not the same and `weather.nc` contains more variables.
I also wouldn't know how to link names like `DWD.M-MPI-ESM-LR.EPISODES2018.r1i1p1.historical` back to the station names like `Norderney`, `coast` and so on (if this is even possible).

I guess that DWD simply provides historical data by default along with the modeled RCP data.

**Comment by mmaelicke** [comment]
This is further tracked in #85 , thus I will close this issue
