### ISSUE TITLE
PyplotGlobalUseWarning whenever a plot is displayed

### ISSUE THREAD

**Issue by AlexDo1** [hydrocode-de/RUINSapp#9]
Whenever a plot is displayed, the following warning appears in the RUINSapp:

![image](https://user-images.githubusercontent.com/23619690/154798594-593ddb45-4fbe-487e-8720-1333c43e4343.png)

Possible fixes are included in the warning message.

**Comment by mmaelicke** [comment]
This was solved for the weather explorer with version `v0.6.0`.
